name: Publish to RubyGems

on:
  workflow_dispatch:

jobs:
  release:
    if: github.repository == 'sena-m09/liquidbook'
    runs-on: ubuntu-latest

    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
      contents: write  # IMPORTANT: this permission is required for `rake release` to push the release tag

    steps:
      - uses: actions/checkout@v6

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true

      - name: Publish to RubyGems
        uses: rubygems/release-gem@v1
